### ISSUE TITLE
DCC example fails with matlab error

### ISSUE THREAD

**Issue by charlie-minns** [shahsohil/DCC#20]
Running `python DCC.py --data mnist --net checkpoint_4.pth.tar --tensorboard --id 1` results in this errors:

```
Traceback (most recent call last):
  File "DCC.py", line 335, in <module>
    main(args)
  File "DCC.py", line 85, in main
    trainset = DCCPT_data(root=datadir, train=True, h5=args.h5)
  File "/Users/charlieminns/Desktop/DCC-master/pytorch/custom_data.py", line 19, in __init__
    data = sio.loadmat(osp.join(root, 'traindata.mat'), mat_dtype=True)
  File "/Users/charlieminns/miniconda3/envs/py37/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 217, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/Users/charlieminns/miniconda3/envs/py37/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 72, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/Users/charlieminns/miniconda3/envs/py37/lib/python3.7/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 51, 55
```

Please advise.

**Comment by shahsohil** [comment]
It has something to do with differing versions of Matlab.
