### ISSUE TITLE
ERROR not create file checkpoint_2.pth.tar  in          easy/results/runs/         only created file checkpoint_0.pth.tar and checkpoint_1.pth.tar     in          easy/results/runs/

### ISSUE THREAD

**Issue by MahdiCmtr** [shahsohil/DCC#31]
![Untitled](https://user-images.githubusercontent.com/52071921/106718361-376aec80-6616-11eb-93af-2696344f3e87.png)
1- !python2 make_data.py --data easy
2- !python2 edgeConstruction.py --dataset easy --samples 600
3- !python2 pretraining.py --data easy --tensorboard --id 1 --niter 500 --dim 1 --lr 0.0001 --step 300
4- !python2 extract_feature.py --data easy --net checkpoint_2.pth.tar --features pretrained --dim 1

 Loaded `easy` dataset for finetuning
The endpoints are Delta1: 0.000, Delta2: 0.005
==> no checkpoint found at '/data/easy/results/checkpoint_2.pth.tar'
Traceback (most recent call last):
  File "DCC.py", line 336, in <module>
    main(args)
  File "DCC.py", line 120, in main
    load_weights(args, outputdir, net)
  File "DCC.py", line 221, in load_weights
    raise ValueError
ValueError

**Comment by shahsohil** [comment]
Is there any problem ? I note that the error is due to missing checkpoint_2.tar file.
